version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - nginx-node-network
    volumes: 
      - ./node:/usr/src/app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-node-network
    restart: always

networks:
  nginx-node-network:
    driver: bridge